language: go

go: "1.11"

env:
  global:
  - LINUX_BINARY=release/attendance-${TRAVIS_TAG}-linux-amd64
  - DARWIN_BINARY=release/attendance-${TRAVIS_TAG}-darwin-amd64
  - LINUX_ARM_BINARY=release/attendance-${TRAVIS_TAG}-linux-arm6

before_script:
- go get

script:
- go test

before_deploy:
- mkdir -p release
- "GOOS=linux  GOARCH=amd64 go build -o ${LINUX_BINARY}"
- "GOOS=darwin GOARCH=amd64 go build -o ${DARWIN_BINARY}"
- "GOOS=linux  GOARCH=arm GOARM=6 go build -o ${LINUX_ARM_BINARY}"

deploy:
  provider: releases
  api_key: ${API_KEY}
  skip_cleanup: true
  file:
  - "${LINUX_BINARY}"
  - "${DARWIN_BINARY}"
  - "${LINUX_ARM_BINARY}"
  on:
    repo: filkra/attendance
    tags: true